server:
  port: 8080
spring:
  mvc:
    favicon:
      enabled: false
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    # hikari配置
    hikari:
      auto-commit: true
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 5
      maximum-pool-size: 20
# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.iszhouhua.blog.model
  type-enums-package: com.iszhouhua.blog.model.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 数据库表前缀
      table-prefix: blog_
      #主键类型
      id-type: auto
      #数据库类型
      db-type: mysql
    banner: false